// Question bank (mix of multiple-choice + short answer)
        // You can edit/add freely.
        window.QUESTION_BANK = [
          {
            cat: "Movies_01",
            diff: 1,
            q: "In Home Alone, where are the McCallisters going for Christmas?",
            choices: ["London", "Paris", "New York", "Rome"],
            a: "Paris",
            fact: "Kevin’s family flies to Paris while he’s left behind.",
          },
          {
            cat: "Movies_02",
            diff: 1,
            q: "What is the name of the snowman in Frozen?",
            choices: ["Sven", "Olaf", "Kristoff", "Marshmallow"],
            a: "Olaf",
            fact: "Olaf is the warm-hug-loving snowman.",
          },
          {
            cat: "TV_01",
            diff: 1,
            q: "Which animated character says: “Bah, humbug!” most famously in many adaptations?",
            choices: ["The Grinch", "Ebenezer Scrooge", "Rudolph", "Santa"],
            a: "Ebenezer Scrooge",
            fact: "Scrooge is from A Christmas Carol.",
          },
          {
            cat: "Traditions_01",
            diff: 1,
            q: "What plant are people traditionally supposed to kiss under?",
            choices: ["Holly", "Mistletoe", "Pine", "Poinsettia"],
            a: "Mistletoe",
            fact: "Mistletoe kissing is a classic holiday trope.",
          },
          {
            cat: "Music_01",
            diff: 1,
            q: "Finish the lyric: “You better watch out, you better not cry…”",
            choices: [
              "Santa Claus is coming to town",
              "Jingle Bells",
              "Silent Night",
              "Deck the Halls",
            ],
            a: "Santa Claus is coming to town",
            fact: "That line is from 'Santa Claus Is Comin’ to Town'.",
          },
          {
            cat: "Music_02",
            diff: 3,
            q: "Mariah Carey’s 'All I Want for Christmas Is You' was originally released in what year?",
            choices: ["1991", "1994", "1998", "2002"],
            a: "1994",
            fact: "It’s been re-charting like a holiday boomerang for years.",
          },
          {
            cat: "Food_01",
            diff: 1,
            q: "What spice is traditionally used in eggnog?",
            choices: ["Cumin", "Nutmeg", "Paprika", "Coriander"],
            a: "Nutmeg",
            fact: "Nutmeg is the classic eggnog topper.",
          },
          {
            cat: "Winter_01",
            diff: 2,
            q: "What is the name of a snowstorm with strong winds that reduce visibility?",
            choices: ["Monsoon", "Blizzard", "Typhoon", "Dust devil"],
            a: "Blizzard",
            fact: "Blizzards are defined by wind + low visibility + snowfall.",
          },
          {
            cat: "Movies_03",
            diff: 1,
            q: "In Elf, what is Buddy’s favorite food group?",
            choices: ["Pancakes", "Candy", "Syrup", "Pizza"],
            a: "Candy",
            fact: "He says: 'Candy, candy canes, candy corns, and syrup!'",
          },
          {
            cat: "Traditions_02",
            diff: 2,
            q: "How many reindeer are named in 'Rudolph the Red-Nosed Reindeer' (the song)?",
            choices: ["6", "8", "9", "10"],
            a: "8",
            fact: "The named ones are 8; Rudolph is added as the 9th in other references.",
          },
          {
            cat: "Pop Culture_01",
            diff: 1,
            q: "Which Hogwarts house colors are red and gold?",
            choices: ["Ravenclaw", "Slytherin", "Gryffindor", "Hufflepuff"],
            a: "Gryffindor",
            fact: "Festive *and* brave.",
          },
          {
            cat: "Fun Facts_01",
            diff: 2,
            q: "What is the most common color of Christmas lights historically used in early electric strands?",
            choices: ["Blue", "Red", "White", "Multicolor"],
            a: "Multicolor",
            fact: "Early strands popularized multi-colored bulbs.",
          },

          {
            cat: "Lightning_01",
            diff: 1,
            q: "Name the green holiday character who tries to steal Christmas.",
            a: "The Grinch",
            fact: "Short answer: accept close matches.",
          },
          {
            cat: "Lightning_02",
            diff: 1,
            q: "What do you hang on a fireplace for presents?",
            a: "Stockings",
            fact: "Also accept 'stocking'.",
          },
          {
            cat: "Lightning_03",
            diff: 1,
            q: "What holiday treat is a striped red-and-white hook-shaped candy?",
            a: "Candy cane",
            fact: "Also accept 'candycanes'.",
          },

          // ADD THESE 15 (to make 30 total)
          {
            cat: "Movies_04",
            diff: 2,
            q: "In The Polar Express, what word is punched into the boy’s ticket?",
            choices: ["BELIEVE", "HOPE", "JOY", "WONDER"],
            a: "BELIEVE",
            fact: "The ticket is punched to spell 'BELIEVE'.",
          },
          {
            cat: "Movies_05",
            diff: 3,
            q: "Which holiday movie is set around a radio station and features a 'lonely hearts' vibe?",
            choices: [
              "Sleepless in Seattle",
              "While You Were Sleeping",
              "Love Actually",
              "Serendipity",
            ],
            a: "Sleepless in Seattle",
            fact: "Not strictly a Christmas-only movie, but a winter classic.",
          },

          {
            cat: "TV_02",
            diff: 3,
            q: "In The Office (US), what is the name of Dwight’s Christmas alter ego?",
            choices: ["Santa Dwight", "Belsnickel", "Krampus", "Jack Frost"],
            a: "Belsnickel",
            fact: "Dwight arrives as Belsnickel to judge who is impish or admirable.",
          },
          {
            cat: "TV_03",
            diff: 2,
            q: "In Friends, what animal does Ross dress as for a holiday party?",
            choices: ["Holiday Armadillo", "Elf", "Reindeer", "Snowman"],
            a: "Holiday Armadillo",
            fact: "The Holiday Armadillo teaches about Hanukkah.",
          },

          {
            cat: "Traditions_03",
            diff: 1,
            q: "What do people traditionally place at the top of a Christmas tree?",
            choices: ["A bell", "A star or angel", "A bow", "A candle"],
            a: "A star or angel",
            fact: "Both are common—pick either if you want to allow both.",
          },
          {
            cat: "Traditions_04",
            diff: 2,
            q: "Which day is known as the day after Christmas in the UK and some Commonwealth countries?",
            choices: ["Boxing Day", "Saint Day", "Wreath Day", "Yule Day"],
            a: "Boxing Day",
            fact: "Boxing Day is December 26.",
          },

          {
            cat: "Music_03",
            diff: 3,
            q: "Which song includes the lyric: “Everyone dancing merrily in the new old-fashioned way”?",
            choices: [
              "Rockin’ Around the Christmas Tree",
              "Jingle Bell Rock",
              "White Christmas",
              "Winter Wonderland",
            ],
            a: "Rockin’ Around the Christmas Tree",
            fact: "That lyric is from 'Rockin’ Around the Christmas Tree'.",
          },
          {
            cat: "Music_04",
            diff: 2,
            q: "What holiday song is traditionally associated with a 'partridge in a pear tree'?",
            choices: [
              "The Twelve Days of Christmas",
              "O Holy Night",
              "Carol of the Bells",
              "Joy to the World",
            ],
            a: "The Twelve Days of Christmas",
            fact: "The partridge kicks off the whole escalating gift list.",
          },

          {
            cat: "Food_02",
            diff: 1,
            q: "What is the main flavor in a classic candy cane?",
            choices: ["Peppermint", "Cinnamon", "Spearmint", "Vanilla"],
            a: "Peppermint",
            fact: "Peppermint is the classic candy cane flavor.",
          },
          {
            cat: "Food_03",
            diff: 1,
            q: "Which cookie is often shaped like a little person and decorated with icing?",
            choices: ["Snickerdoodle", "Gingerbread", "Shortbread", "Macaron"],
            a: "Gingerbread",
            fact: "Gingerbread people are a holiday staple.",
          },

          {
            cat: "Winter_02",
            diff: 2,
            q: "What is the name for frozen rain that forms a glaze on surfaces?",
            choices: ["Hail", "Sleet", "Freezing rain", "Frost"],
            a: "Freezing rain",
            fact: "It creates that dangerous glassy ice layer.",
          },
          {
            cat: "Winter_03",
            diff: 1,
            q: "What do you call the layer of ice crystals that forms on surfaces overnight?",
            choices: ["Dew", "Frost", "Mist", "Fog"],
            a: "Frost",
            fact: "Frost forms when water vapor freezes on cold surfaces.",
          },

          {
            cat: "Pop Culture_02",
            diff: 3,
            q: "Which fictional winter holiday figure is known for visiting kids on December 6 in some European traditions?",
            choices: [
              "Krampus",
              "Saint Nicholas",
              "The Tooth Fairy",
              "The Sandman",
            ],
            a: "Saint Nicholas",
            fact: "Saint Nicholas Day traditions vary by country.",
          },

          {
            cat: "Fun Facts_02",
            diff: 2,
            q: "Which U.S. state has a town named Santa Claus?",
            choices: ["Indiana", "Ohio", "Colorado", "Vermont"],
            a: "Indiana",
            fact: "Santa Claus, Indiana is real—and very on-brand.",
          },

          {
            cat: "Lightning_04",
            diff: 2,
            q: "Name one of Santa’s reindeer (any one).",
            a: "Dasher/Dancer/Prancer/Vixen/Comet/Cupid/Donner/Blitzen/Rudolph",
            fact: "Accept any correctly spelled (or close) reindeer name.",
          },
        ];